### ISSUE TITLE
st_slowwave.m at line 798 - question on used array for thresholding

### ISSUE THREAD

**Issue by matpadalino87** [Frederik-D-Weber/sleeptrip#4]
Dear all,

I've a question about your function "st_slowwaves.m ".

At line 798 :
![issue_st_slowwave](https://user-images.githubusercontent.com/115818787/236521155-d6e4751a-3c40-4de7-9957-cc7ebe7d3088.JPG)

I noticed that for the first condition in the IF the mean negative value weigthed for the factor is compared with "trl_detectedTroughsSamples", but if I understand well it'd be with "trl_detectedSignalMin". Is'n it so?

I apologize if I'm not right.

Thank for your attention.

Matteo Padalino

**Comment by Frederik-D-Weber** [comment]
Nice catch Matteo! 

Thank you, much appreciated.

Lucky the samples were actually seconds in the recording, so for longer recordings with more than a few hundred seconds did not affect anything. That is likely why this never showed up in test cases when changed from operations in samples to actual time points in the data (which is more precise).

New default behavior should also get back to the pre-legacy behavior of also considering in addition to the amplitude the down peakthe down peak (so detect a bit less slow waves if the shape does not fit). 

I fixed and cleared things up with the latest commit.
